
trigger:
  branches:
    include:
    - master
  tags:
    exclude:
    - 'v*'

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'
- script: |
    git config --global user.email 'azdo-ci@geoanalytics.group'
    git config --global user.name 'AzDO Pipeline'
    git checkout $(Build.SourceBranchName)
  displayName: 'Setup Git'
- script: |
    export newversion = $(npm version patch -m "[skip ci] Upgrade to version %s")
    cd projects/portal-core-ui/
    npm version $newversion
  displayName: 'Bump package version'
- script: |
    npm install -g npm@7
    npm install -g @angular/cli@11
    npm install
    ng build portal-core-ui --prod
  displayName: 'npm install and build'
- script: |
    git push origin $(Build.SourceBranchName)
    git push origin --tags
  displayName: 'Git Push back to repo'
- task: Npm@1
  inputs:
    command: 'publish'
    workingDir: 'dist/portal-core-ui'
    publishEndpoint: 'npmjs-auscope-update'
