
trigger:
  branches:
    include:
    - master
    - Release-*
  tags:
    exclude:
    - 'v*'

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '18.x'
  displayName: 'Install Node.js'
- script: |
    git config --global user.email 'azdo-ci@geoanalytics.group'
    git config --global user.name 'AzDO Pipeline'
    git checkout $(Build.SourceBranchName)
  displayName: 'Setup Git'
- script: |
    cd projects/portal-core-ui/
    mkdir '.git'
    npm version patch -m "[skip ci] Upgrade to version %s"
  displayName: 'Bump package version'
- script: |
    npm install -g npm@9
    npm install -g @angular/cli@15
    npm install
    ng build --configuration production portal-core-ui
  displayName: 'npm install and build'
- script: |
    git push origin $(Build.SourceBranchName)
    git push origin --tags
  displayName: 'Git Push back to repo'
- task: Npm@1
  inputs:
    command: 'publish'
    workingDir: 'dist/portal-core-ui'
    publishEndpoint: 'npmjs-auscope-update'
