# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy to npmjs

on:
  push:
    branches: [ master ]

jobs: 
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install 
      - run: npm link @angular/cli
      - run: ng build portal-core-ui --configuration production
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: dist/portal-core-ui/package.json
          access: public
          # Change dry-run to true for testing
          dry-run: false
          strategy: all
          
        
